
services:
  # -----------------------------
  # Adminer (interface de DB)
  # -----------------------------
  manager:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring

  # -----------------------------
  # PostgreSQL
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: Postgres_Admin  # Nome consistente com SQL
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: Grafana_DB  # Nome consistente com SQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume persistente ativado
      - ./infrastructure/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./infrastructure/02_tables.sql:/docker-entrypoint-initdb.d/02_tables.sql
    ports:
      - "5432:5432"  # Porta fixa para evitar problemas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Postgres_Admin"]  # Usuário correto
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  # -----------------------------
  # Grafana
  # -----------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: Grafana_DB  # Nome consistente
      GF_DATABASE_USER: Postgres_Admin  # Usuário consistente
      GF_DATABASE_PASSWORD: secure_password_123
      GF_DATABASE_SSL_MODE: disable
      GF_SECURITY_ADMIN_USER: grafana_admin  # Admin do Grafana (diferente do DB)
      GF_SECURITY_ADMIN_PASSWORD: secure_password_123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Volume persistente ativado
    networks:
      - monitoring

  # -----------------------------
  # Python App
  # -----------------------------
  python-app:
    build: ./python-app
    container_name: python_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://Postgres_Admin:secure_password_123@postgres:5432/Grafana_DB
    volumes:
      - ./python-app:/app  # Volume para desenvolvimento
    working_dir: /app
    command: >
      sh -c "echo '🐍 Executando main.py...' &&
             python -u main.py &&
             echo '✅ Execução concluída com sucesso!' &&
             echo '⏳ Mantendo container ativo para debugging...' &&
             tail -f /dev/null"
    restart: unless-stopped
    networks:
      - monitoring

# -----------------------------
# Volumes
# -----------------------------
volumes:
  postgres_data:
  grafana_data:

# -----------------------------
# Networks
# -----------------------------
networks:
  monitoring:
    driver: bridge